#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("nl.pleduc.TsumTsumHeartTracker.Resource", IsApplication=true)]

namespace nl.pleduc.TsumTsumHeartTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int sorting_types = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int maxValue = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int minValue = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_autorenew_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_copy_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_cut_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_paste_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_search_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_settings_white_48dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090009
			public const int context = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout2 = 2131296257;
			
			// aapt resource value: 0x7f09000b
			public const int menu_refresh = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int menu_reset = 2131296269;
			
			// aapt resource value: 0x7f09000a
			public const int menu_search = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int menu_settings = 2131296268;
			
			// aapt resource value: 0x7f090008
			public const int preference_numberpicker = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int preference_numberpicker_dialog = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int scrollView1 = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int spinner1 = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int tableLayout1 = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int tableRow1 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int textView1 = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int toolbar = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int preference_numberpicker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int toolbar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar_menu_main = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int actionbar_menu_settings = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationNameShort = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int sorting_prompt = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CustomThemes_TsumTsum = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int searchable = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] NumberPickerPreference = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int NumberPickerPreference_maxValue = 1;
			
			// aapt resource value: 0
			public const int NumberPickerPreference_minValue = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
